Resources:
    AutobuilderJobsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.JobsQueueName}
        VisibilityTimeout: 600
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [JobsDLQ, Arn]
          maxReceiveCount: 1
    AutobuilderJobUpdatesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.JobUpdatesQueueName}
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [JobUpdatesDLQ, Arn]
          maxReceiveCount: 1
    JobsDLQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.JobsDLQueueName}
    JobUpdatesDLQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.JobUpdatesDLQueueName}