GIT_BRANCH=$(shell git rev-parse --abbrev-ref HEAD)

SNOOTY_ENV = $(shell printenv SNOOTY_ENV)

ifeq ($(STAGING_USERNAME),)
	USER=$(shell whoami)
else
	USER=$(STAGING_USERNAME)
endif
STAGING_URL="https://docs-mongodborg-staging.corp.mongodb.com"
STAGING_BUCKET=docs-mongodb-org-stg

ifeq ($(SNOOTY_ENV), production) 
	PRODUCTION_URL="https://docs.mongodb.com"
	PRODUCTION_BUCKET=docs-mongodb-org-prd
else ifeq ($(SNOOTY_ENV), staging)
	PRODUCTION_URL="https://docs-mongodborg-staging.corp.mongodb.com"
	PRODUCTION_BUCKET=docs-mongodb-org-stg
else ifeq ($(SNOOTY_ENV), regression)
	PRODUCTION_URL="https://docs-mongodborg-integration.corp.mongodb.com"
	PRODUCTION_BUCKET=docs-mongodb-org-intgr
endif

PROJECT=database-tools
MUT_PREFIX ?= $(PROJECT)

COMMIT_HASH=$(shell git rev-parse --short HEAD)
REPO_DIR=$(shell pwd)

SNOOTY_DB_USR = $(shell printenv MONGO_ATLAS_USERNAME)
SNOOTY_DB_PWD = $(shell printenv MONGO_ATLAS_PASSWORD)

include ~/shared.mk

	
get-build-dependencies: 
	@curl https://raw.githubusercontent.com/mongodb/docs-worker-pool/meta/publishedbranches/docs-commandline-tools.yaml > ${REPO_DIR}/published-branches.yaml
	