GIT_BRANCH=$(shell git rev-parse --abbrev-ref HEAD)

USER=$(shell whoami)
SNOOTY_INTEGRATION=false


COMMIT_HASH=$(shell git rev-parse --short HEAD)

PREFIX=csfle-merge
PROJECT=csfle-merge
MUT_PREFIX ?= $(PROJECT)
REPO_DIR=$(shell pwd)

SNOOTY_DB_USR = $(shell printenv MONGO_ATLAS_USERNAME)
SNOOTY_DB_PWD = $(shell printenv MONGO_ATLAS_PASSWORD)

include ~/shared.mk