Resources:
  DocsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${self:custom.bucketName}
      WebsiteConfiguration:
          IndexDocument: index.html
          RoutingRules:
            - RoutingRuleCondition:
                KeyPrefixEquals: ${self:custom.site.prefix.${self:provider.stage}}/realm/cloud
              RedirectRule:
                Protocol: "https"
                HostName: ${self:custom.site.host.${self:provider.stage}}
                ReplaceKeyPrefixWith: ${self:custom.site.prefix.${self:provider.stage}}/atlas/app-services

  DocAtlasBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${self:custom.atlasBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html

  CloudManagerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${self:custom.cloudManagerBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html

  OpsManagerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${self:custom.opsManagerBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html

  JavaBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${self:custom.javaBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html

  GoBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${self:custom.goBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html

  NodeBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${self:custom.nodeBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html

  DocsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DocsBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - Fn::Join: ['', [{ "Fn::GetAtt": ["DocsBucket", "Arn" ] }, '/*']]
              - Fn::Join: ['', [{ "Fn::GetAtt": ["DocsBucket", "Arn" ] }]]

  DocAtlasBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DocAtlasBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["DocAtlasBucket", "Arn" ] }, '/*']]

  CloudManagerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: CloudManagerBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["CloudManagerBucket", "Arn" ] }, '/*']]

  OpsManagerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: OpsManagerBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["OpsManagerBucket", "Arn" ] }, '/*']]

  JavaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: JavaBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["JavaBucket", "Arn" ] }, '/*']]

  GoBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: GoBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["GoBucket", "Arn" ] }, '/*']]

  NodeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: NodeBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["NodeBucket", "Arn" ] }, '/*']]
