Resources:
  SecurityGroupVPC:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: vpc-781fab13
      GroupDescription: 'Security group to VPC'

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: ${self:service}-${self:provider.stage}
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: ${self:service}-${self:provider.stage}
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: ${self:custom.ecs.containerCpu.${self:provider.stage}}
      Memory: ${self:custom.ecs.containerMemory.${self:provider.stage}}
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: ${self:service}-${self:provider.stage}
          Image: ${self:custom.ecs.imageUrl}
          Cpu: ${self:custom.ecs.containerCpu.${self:provider.stage}}
          Memory: ${self:custom.ecs.containerMemory.${self:provider.stage}}
          PortMappings:
            - ContainerPort: ${self:custom.ecs.port}
              Protocol: tcp
          Environment:
            - Name: SNOOTY_ENV
              Value: ${self:custom.env.${self:provider.stage}}
            - Name: MONGO_ATLAS_USERNAME
              value: ${self:custom.dbUsername}
            - Name: MONGO_ATLAS_PASSWORD
              value: ${self:custom.dbPassword}
            - Name: DB_NAME
              value: ${self:custom.dbName}
            - Name: AWS_ACCESS_KEY_ID
              value: ${self:custom.awsKey}
            - Name: AWS_SECRET_ACCESS_KEY
              value: ${self:custom.awsSecret}
            - Name: GITHUB_BOT_USERNAME
              value: ${self:custom.githubBotUserName}
            - Name: GITHUB_BOT_PASSWORD
              value: ${self:custom.githubBotPW}
            - Name: FASTLY_TOKEN
              value: ${self:custom.fastlyToken}
            - Name: FASTLY_DOCHUB_MAP
              value: ${self:custom.fastlyDochubMap}
            - Name: FASTLY_SERVICE_ID
              value: ${self:custom.fastlyServiceId}
            - Name: COL_NAME
              value: ${self:custom.collection}
            - Name: NPM_BASE_64_AUTH
              value: ${self:custom.npmBase64Auth}
            - Name: NPM_EMAIL
              value: ${self:custom.npmEmail}
            - Name: AWS_ACCESS_KEY_ID_DEVHUB
              value: ${self:custom.awsKeyDevhub}
            - Name: AWS_SECRET_ACCESS_KEY_DEVHUB
              value: ${self:custom.awsSecretDevhub}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'LogGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ${self:provider.stage}

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ${self:service}-${self:provider.stage}

  ExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  TaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'

  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      LaunchType: FARGATE
      ServiceName: ${self:service}-${self:provider.stage}
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: ${self:custom.ecs.minimumHealthyPercent.${self:provider.stage}}
        MaximumPercent: ${self:custom.ecs.maximumPercent.${self:provider.stage}}
      DesiredCount: ${self:custom.ecs.desiredCount.${self:provider.stage}}
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-8c3623f6
            - subnet-a4ac73cf
            - subnet-9e83fed2
          SecurityGroups:
            - !Ref SecurityGroupVPC