Resources:
  SecurityGroupVPC:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: vpc-03701c29a3408c714
      GroupDescription: 'Security group to VPC'

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: ${self:service}-${self:provider.stage}
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: ${self:service}-${self:provider.stage}
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: ${self:custom.ecs.containerCpu.${self:provider.stage}}
      Memory: ${self:custom.ecs.containerMemory.${self:provider.stage}}
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: ${self:service}-${self:provider.stage}
          Image: ${self:custom.ecs.imageUrl}
          Cpu: ${self:custom.ecs.containerCpu.${self:provider.stage}}
          Memory: ${self:custom.ecs.containerMemory.${self:provider.stage}}
          Environment:
            - Name: STAGE
              value: ${self:provider.stage}
            - Name: SNOOTY_ENV
              Value: ${self:custom.env.${self:provider.stage}}
            - Name: MONGO_ATLAS_USERNAME
              Value: ${self:custom.dbUsername}
            - Name: MONGO_ATLAS_PASSWORD
              Value: ${self:custom.dbPassword}
            - Name: MONGO_ATLAS_HOST
              Value: ${self:custom.dbhost}
            - Name: MONGO_ATLAS_URL
              Value: mongodb+srv://${self:custom.dbUsername}:${self:custom.dbPassword}@${self:custom.dbhost}/admin?retryWrites=true
            - Name: DB_NAME
              Value: ${self:custom.dbName}
            - Name: AWS_ACCESS_KEY_ID
              Value: ${self:custom.awsKey}
            - Name: AWS_SECRET_ACCESS_KEY
              Value: ${self:custom.awsSecret}
            - Name: GITHUB_BOT_USERNAME
              Value: ${self:custom.githubBotUserName}
            - Name: GITHUB_BOT_PASSWORD
              Value: ${self:custom.githubBotPW}
            - Name: FASTLY_DOCHUB_MAP
              Value: ${self:custom.fastlyDochubMap}
            - Name: JOB_QUEUE_COL_NAME
              Value: ${self:custom.jobCollection}
            - Name: REPO_BRANCHES_COL_NAME
              value:  ${self:custom.repoBranchesCollection}
            - Name: NPM_BASE_64_AUTH
              Value: ${self:custom.npmBase64Auth}
            - Name: NPM_EMAIL
              Value: ${self:custom.npmEmail}
            - Name: AWS_ACCESS_KEY_ID_DEVHUB
              Value: ${self:custom.awsKeyDevhub}
            - Name: AWS_SECRET_ACCESS_KEY_DEVHUB
              Value: ${self:custom.awsSecretDevhub}
            - Name: GATSBY_BASE_URL
              Value: ${self:custom.gatsbyBaseUrl}
            - Name: GATSBY_FEATURE_FLAG_CONSISTENT_NAVIGATION
              Value: ${self:custom.gatsbyFeatureFlagConsistentNavigation}
            - Name: GATSBY_FEATURE_FLAG_SDK_VERSION_DROPDOWN
              Value: ${self:custom.gatsbyFeatureFlagVersionDropdown}
            - Name: FASTLY_MAIN_TOKEN
              Value: ${self:custom.fastlyMainToken}
            - Name: FASTLY_MAIN_SERVICE_ID
              Value: ${self:custom.fastlyMainServiceId}
            - Name: FASTLY_DOCHUB_SERVICE_ID
              Value: ${self:custom.fastlyDochubServiceId}
            - Name: FASTLY_DOCHUB_TOKEN
              Value: ${self:custom.fastlyDochubToken}
            - Name: FASTLY_ATLAS_TOKEN
              Value: ${self:custom.fastlyAtlasToken}
            - Name: FASTLY_ATLAS_SERVICE_ID
              Value: ${self:custom.fastlyAtlasServiceId}
            - Name: FASTLY_DEVHUB_TOKEN
              Value: ${self:custom.fastlyDevhubToken}
            - Name: FASTLY_DEVHUB_SERVICE_ID
              Value: ${self:custom.fastlyDevhubServiceId}
            - Name: FASTLY_OPS_MANAGER_TOKEN
              Value: ${self:custom.fastlyOpsManagerToken}
            - Name: FASTLY_OPS_MANAGER_SERVICE_ID
              Value: ${self:custom.fastlyOpsManagerServiceId}
            - Name: FASTLY_CLOUD_MANAGER_TOKEN
              Value: ${self:custom.fastlyCloudManagerToken}
            - Name: FASTLY_CLOUD_MANAGER_SERVICE_ID
              Value: ${self:custom.fastlyCloudManagerServiceId}
            - Name: USER_ENTITLEMENT_COL_NAME
              Value: ${self:custom.entitlementCollection}
            - Name: JOBS_QUEUE_URL
              Value: ${self:custom.jobsQueueUrl}
            - Name: JOB_UPDATES_QUEUE_URL
              Value: ${self:custom.jobUpdatesQueueUrl}
            - Name: CDN_CLIENT_ID
              Value: ${self:custom.cdnClientID}
            - Name: CDN_CLIENT_SECRET
              Value: ${self:custom.cdnClientSecret}
            - Name: CDN_INVALIDATOR_SERVICE_URL
              Value: ${self:custom.cdnInvalidatorServiceURL.${self:provider.stage}} 

          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'LogGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ${self:provider.stage}

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ${self:service}-${self:provider.stage}

  ExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  TaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
          - PolicyName: AllowSQSAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'sqs:SendMessage'
                  Resource: 
                    - 'arn:aws:sqs:us-east-2:216656347858:autobuilder-job-updates-queue-${self:provider.stage}'
                    - 'arn:aws:sqs:us-east-2:216656347858:autobuilder-jobs-queue-${self:provider.stage}'
          - PolicyName: AllowSSMAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'ssm:GetParameter'
                  Resource: "*"

