name: build-docker-ecr

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      context:
        type: string
        required: false
        default: .
      region:
        type: string
        required: true
    secrets:
      ecr_access_key:
        required: true
      ecr_secret_key:
        required: true
      build_args:
        required: false
      build_secrets:
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: config-environment
        env:
          branch: ${{ github.github.head_ref || github.ref_name }}
          commit: ${{ github.sha }}
          number: ${{ github.run_number }}
          name  : ${{ inputs.name }}
        run: |
          echo "branch=${branch//\//-}" >> $GITHUB_ENV
          echo "commit=${commit:0:7}"   >> $GITHUB_ENV
          echo "number=${number}"       >> $GITHUB_ENV
          echo "name=${name}"           >> $GITHUB_ENV

      - name: setup-buildx
        uses: docker/setup-buildx-action@v2

      - name: config-aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.ecr_access_key }}
          aws-secret-access-key: ${{ secrets.ecr_secret_key }}
          aws-region:            ${{ inputs.region }}

      - name: login-ecr
        id:   login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: login-ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: config-environment
        env:
          ecr_registry: ${{ steps.login-ecr.outputs.registry }}
          github_image: ghcr.io/${{ github.repository }}/${{ env.name }}
        run: |
          echo "ecr_registry=${ecr_registry}" >> $GITHUB_ENV
          echo "github_image=${github_image}" >> $GITHUB_ENV

      - name: docker-build-publish
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push:    true
          tags: |
            ${{ env.ecr_registry }}/${{ env.name }}:${{ env.branch }}
            ${{ env.ecr_registry }}/${{ env.name }}:${{ env.branch }}-${{ env.commit }}
            ${{ env.ecr_registry }}/${{ env.name }}:github-${{ env.number }}
          build-args: ${{ secrets.build_args }}
          secrets:    ${{ secrets.build_secrets }}
          cache-from: type=registry,ref=${{ env.github_image }}:${{ env.branch }}-cache
          cache-to:   type=registry,ref=${{ env.github_image }}:${{ env.branch }}-cache,mode=max
