on:
  push:
    tags:
      - 'v*'
name: Deploy Production
jobs:
  deploy-production-1:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.0
        with:
          key: ${{ secrets.EC2_RSA_KEY }}
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }}
          name: id_rsa
      - name: SSH to Production 1
        run: |
          ssh -l ubuntu ${{ secrets.PRODUCTION_HOST_1}} -T '
          cd docker/docs-worker-pool
          git fetch origin
          git checkout $(git describe --tags)
          sudo docker system prune
          sudo docker build --no-cache --tag production .
          sudo docker stop $(sudo docker ps -a -q)
          sudo sh rundocker.sh
          '
  deploy-production-2:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.0
        with:
          key: ${{ secrets.EC2_RSA_KEY }}
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }}
          name: id_rsa
      - name: SSH to Production 2
        run: |
          ssh -l ubuntu ${{ secrets.PRODUCTION_HOST_2}} -T '
          cd docker/docs-worker-pool
          git fetch origin
          git checkout $(git describe --tags)
          sudo docker system prune
          sudo docker build --no-cache --tag production .
          sudo docker stop $(sudo docker ps -a -q)
          sudo sh rundocker.sh
          '
          
