name: CI

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'modules/**'
  pull_request:
    branches:
    - master
    - DOP-3420
    paths-ignore:
    - 'modules/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install --dev
    - name: Lint
      run: npm run lint && npm run format
    - name: Test
      run: npm test
