name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  # Checks for changes outside of /modules directory
  changes:
    runs-on: ubuntu-latest
    outputs:
      autobuilder: ${{ steps.filter.outputs.autobuilder }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # set autobuilder filter true
        # if any changes outside of modules directory
        filters: |
          autobuilder:
            - '!(modules/**)'

  test:
    needs: changes
    if: ${{ needs.changes.outputs.autobuilder }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install --dev
    - name: Lint
      run: npm run lint && npm run format
    - name: Test
      run: npm test
