# skip required checks due to "paths-ignore" filter on jobs
name: CI-persistence

on:
  push:
    branches:
    - master
    paths-ignore:
    - '!modules/persistence/**'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '!modules/persistence/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
