name: CI-persistence

on:
  push:
    branches:
    - master
    paths:
      - 'modules/persistence/**'
  pull_request:
    branches:
    - master
    paths:
      - 'modules/persistence/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        cd modules/persistence
        npm ci
    - name: Lint
      run: |
        cd modules/persistence
        npm run lint
    - name: Test
      run: |
        cd modules/persistence
        npm test
