# skip required checks due to "paths-ignore" filter on jobs
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

name: CI

on:
  push:
    branches:
    - master
    paths:
    - 'modules/**'
  pull_request:
    branches:
    - master
    paths:
    - 'modules/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
