# NOTE: This will be removed on merge of PR
on:
  push:
    branches:
      - DOP-4171

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Get Webhook URL 
        uses: mongodb/docs-worker-actions/rebuild-parse-cache@DOP-4294
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_SHA: ${{ github.sha }}
          WORKSPACE: ${{ github.workspace }}