name: CI - OAS Page Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Checks for changes to the modules/oas-page-builder directory
  changes:
    runs-on: ubuntu-latest
    outputs:
      oas: ${{ steps.filter.outputs.oas }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            oas:
              - 'modules/oas-page-builder/**'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.oas == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/oas-page-builder
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Format and lint
        run: npm run format && npm run lint
      - name: Test
        run: npm run test
